name: Labeller

on:    
  workflow_call:
    inputs:
      label_name:
        description: 'Label name'
        required: true
        default: 'community'
      label_color:
        description: 'Label color'
        required: true
        default: '5319e7'
      org_membership:
        description: 'Organization membership'
        required: true
        default: puppetlabs

jobs:
  communityLabeller:
    runs-on: ubuntu-latest
    steps:
      - name: Label issues or pull requests
        uses: puppetlabs/community-labeller@v0
        with:
          label_name: ${{ inputs.label_name }}
          label_color: ${{ inputs.label_color }}
          org_membership: ${{ inputs.org_membership }}
          token: ${{ secrets.IAC_COMMUNITY_LABELER }}

  labelValidator:
    name: Validate label exists
    runs-on: ubuntu-latest
    steps:
      - name: Check for Labels
        uses: actions/github-script@v6
        with:
          script: |
            async function getPullRequest() {
              // Get current pull request labels
              const { data: { labels } } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.number,
              });

              // Log found label names
              for (const label of labels) {
                core.info(`Found label named '${label.name}' on pull request number ${context.payload.number}`);
              };

              // Fail workflow if no labels exist
              labelsExist = (labels.length === 0) ? false : true;
              if (!labelsExist) core.setFailed(`Please ensure that a label exists on pull request number ${context.payload.number}`);
            }

            getPullRequest();